spring:
  application:
    name: jfsc-sys
  thymeleaf:
    prefix: classpath:/templates/
    mode: HTML
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html
  datasource:
    name: bjexamDB
    url: jdbc:mysql://172.24.202.76:5306/tpsdb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: regadmin
    password: reg@123#!
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    password: IS%5xH5WJASzj*sJ
    host: 10.15.5.95
    port: 7001
    timeout: 10000
    database: 0
    maxTotal: 1000
    maxWaitMillis: 1000
    minEvictableIdleTimeMillis: 300000
    numTestsPerEvictionRun: 1024
    timeBetweenEvictionRunsMillis: 30000
    testOnBorrow: true
    testWhileIdle: true
    sentinel:
      master: mymaster
      nodes: 10.15.5.95:17841,10.15.5.95:17842,10.15.5.95:17843
server:
  port: 80
  servlet:
    session:
      tracking-modes: cookie
      cookie:
        http-only: true
    context-path: /jfsc-sys


